k9s:
  cluster: arn:aws:eks:us-east-2:447542674857:cluster/stage-Fn8wxweP
  namespace:
    active: gloo-system
    lockFavorites: false
    favorites:
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
